name: deuteron
channels:
  - conda-forge
  - defaults
dependencies:
  - cvxpy
  - iminuit
  - pip
  - pytest
  - python=3.7.5
  - pip:
    - jupyter
    - jupyterlab
    - matplotlib
    - noisyopt
    - numpy
    - openfermion==0.11.0
    - pandas
    - pyyaml
    - qiskit==0.19.2
    - scipy
    - seaborn
    - tqdm
    - qutip
